### ISSUE TITLE
RUVSeq input

### ISSUE THREAD

**Issue by ghost** [drisso/archive-RUVSeq#13]
Hello,  

I just have questions about RUVSeq inputs. 
in the manula, it says it need three inputs.
1) expression data : gene level read counts (tophat - htseq)
2) negative control genes
3) contered(technical) replicate/ negative control sampels

I have total six 1X75 nextseq mouse samples, 3 biological samples in each condition.

for the second input, 1) do I need to have list of genes, or sequnece (ERCC spike ins or house keepin genes) and 2) where can i find them (mouse for example)? 
3) If i need a list of sequences as "sebrafishRNASeq" package, do i need to rebuild reference files(fasta, gtf files) for mapping? 

Also, for third input, can i use biological replicate not technical?   

Thank you in advancce, 

Best,
young

**Comment by drisso** [comment]
Dear @coolucy, GH issues are for bug reports only, please use the Bioconductor support forum for help and questions: http://support.bioconductor.org. This way, the whole community will benefit from the Q&A and will be able to contribute to the discussion.

**Comment by drisso** [comment]
I don't understand what you mean in your question 3. But for 1) and 2) all you need is a list of gene IDs that do not change with your biological variable of interest. This depends on your system / application, so I cannot help you here. There exist general list of housekeeping genes that may be used as negative controls, e.g., 
http://www.tau.ac.il/~elieis/Housekeeping_genes.html

Reading our follow-up paper available here:
http://nar.oxfordjournals.org/content/43/16/7664.short

tutorial here:
https://github.com/drisso/peixoto2015_tutorial

may be good for you. There we do use biological replicates, and RUVs seems to work fine.
