### ISSUE TITLE
vignette script issue

### ISSUE THREAD

**Issue by kobeho24** [drisso/archive-RUVSeq#14]
In section 2.1 Filtering and exploratory data analysis
There are some error in regular expression syntax, I suppose.
In particular,
genes <- rownames(filtered)[grep("ˆENS", rownames(filtered))]
spikes <- rownames(filtered)[grep("ˆERCC", rownames(filtered))]
should be
genes <- rownames(filtered)[grep("ENS", rownames(filtered))]
spikes <- rownames(filtered)[grep("ERCC", rownames(filtered))]

**Comment by drisso** [comment]
The regex syntax seems fine. Make sure that you use the actual "^" character (which means beginning). Copy/pasting from the pdf can create issues.
