### ISSUE TITLE
S method on chosen group

### ISSUE THREAD

**Issue by Drwhit** [drisso/archive-RUVSeq#17]
Thanks for this amazing package.  One request if I may. 

My understanding is that when using method "S", the algorithm choses the largest group for generating the correction model.  Could an option be added so that the user can choose the group.  In my case, I have some technical replicates in each batch, and I would like to use them for correction.

**Comment by drisso** [comment]
Hi @Drwhit ,

I'm really sorry for having missed this issue. I somehow never saw it. 

If this is still relevant, please note that we do not use the largest group for generating the correction but we always use all the groups provided by the user.
