### ISSUE TITLE
return exp(normCount) - epsilon

### ISSUE THREAD

**Issue by drisso** [drisso/archive-RUVSeq#6]
Since we log(count+epsilon), we should exp(normCount)-epsilon to be on the same scale

**Comment by drisso** [comment]
Commit 26803c09b1c0e3b7b36246c3b02eca675edf011e in develop should take care of this. Issue still open until merged with master.

**Comment by zhouqz** [comment]
In my last study, I have used the CPM as the expression unit. Here, I want
to use the same expression unit. I see that I can simply use the
normalizedCounts from RUVSeq to do the comparison between samples. But If I
can get the RUV's adjusted CPM, It will be better for me.
