### ISSUE TITLE
RUVSeq DE analysis for data with replicate samples and 4 conditions

### ISSUE THREAD

**Issue by sharvari14** [drisso/archive-RUVSeq#7]
Hello,

I have a question on using RUVSeq for removing batch effects for 8 samples of RNA-Seq data  - 2 batches with 4 samples each.

The example data in the tutorial shows 2 conditions with 3 replicates each:
https://www.bioconductor.org/packages/release/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf

Following the steps in section 3 to estimate factors of unwanted variation using replicate samples, I am trying to define the matrix as:
differences <- matrix(data=c(1:2,3:4,5:6,7:8), byrow=TRUE, nrow=2)
PCA plot for set3 doesn't group the replicates:
![image](https://cloud.githubusercontent.com/assets/7240579/9553150/1e073464-4d8b-11e5-8f0c-3b5d7e16f97e.png)

However, if I define matrix for pairwise condition as:

> differences1 <- matrix(data=c(1:2,3:4), byrow=TRUE, nrow=2)
> set3_1 <- RUVs(set, genes, k=1, differences1)
> plotPCA(set3_1, col=colors[x], cex=1.2)
> and
> differences2 <- matrix(data=c(5:6,7:8), byrow=TRUE, nrow=2)
> set3_2 <- RUVs(set, genes, k=1, differences2)
> plotPCA(set3_2, col=colors[x], cex=1.2)

The PCA plot for each shows grouping of replicates for the 1st 2 conditions.

Could you please let me know what is the correct approach to remove batch effects from replicates and do DE analysis for pairs of conditions : Control vs. KD and Control75 vs. KD75

> set
> SeqExpressionSet (storageMode: lockedEnvironment)
> assayData: 18201 features, 8 samples 
>   element names: counts, normalizedCounts, offset 
> protocolData: none
> phenoData
>   sampleNames: Control_1 Control_2 ... KD75_2 (8 total)
>   varLabels: x
>   varMetadata: labelDescription
> featureData: none
> experimentData: use 'experimentData(object)'
> Annotation:  
> pData(set)
>                         x
> Control_1     Control
> Control_2     Control
> KD_1         KD
> KD_2         KD
> Control75_1 Control75
> Control75_2 Control75
> KD75_1     KD75
> KD75_2     KD75

Thanks for all the help.
Sharvari

**Comment by sharvari14** [comment]
Correction:

> set
> SeqExpressionSet (storageMode: lockedEnvironment)
> assayData: 18201 features, 8 samples 
>   element names: counts, normalizedCounts, offset 
> protocolData: none
> phenoData
>   sampleNames: Scrambled_1 Scrambled_2 ... CNOT7KD75_2 (8 total)
>   varLabels: x
>   varMetadata: labelDescription
> featureData: none
> experimentData: use 'experimentData(object)'
> Annotation:  
> pData(set)
>                         x
> Scrambled_1     Scrambled
> Scrambled_2     Scrambled
> CNOT7KD_1         CNOT7KD
> CNOT7KD_2         CNOT7KD
> Scrambled75_1 Scrambled75
> Scrambled75_2 Scrambled75
> CNOT7KD75_1     CNOT7KD75
> CNOT7KD75_2     CNOT7KD75

**Comment by dtenenba** [comment]
@sharvari14 it doesn't sound like you are reporting an issue with the package. You should be asking on the support site: https://support.bioconductor.org/ . Be sure and tag your question with the package name (RUVSeq).

**Comment by sharvari14** [comment]
Sorry about that.

I just posted the question in support.bioconductor.org..

Would appreciate any help.

thanks
Sharvari

**Comment by drisso** [comment]
Yes, please, post your question on the bioconductor support site.

**Comment by sharvari14** [comment]
Hello Davide,

I did post my question on Bioconductor. Would really appreciate if someone
could help me with RUVSeq DE analysis.

Thanks
Sharvari

**Comment by sharvari14** [comment]
Sorry, just saw your post.
Thanks
